Added `DefaultBtreeMap` and a `set_default` method.
JelteF/defaultmap pull request #10
Opened 2020-08-30 18:40 UTC by rljacobson

Added `DefaultBtreeMap` and a `set_default` method to both `HashMap` and `DefaultBTreeMap`.

2020-09-06 12:01 UTC, JelteF requested changes
Thanks for the work on this, but the way this PR is currently structered makes it very hard to review. Mainly because it does all kinds of refactors together with functionality changes. Can you change this PR to only do functionality changes?

Also, I just merged another PR with serde support. Please update this PR to include that as well.

2020-09-06 12:01 UTC, JelteF commented on src/btreemap.rs
> +/*!
This commment should only be part of the main module. It just clutters the docs if it's on every page.

2020-09-06 12:01 UTC, JelteF commented on src/hashmap.rs
> +use std::borrow::Borrow;
Can you leave the hashmap implementation in the `src/lib.rs` file? Now I have no clue what you changed here, because the git diff shows it all as new.

2020-09-06 12:01 UTC, JelteF commented on src/lib.rs
> +/*!
Please leave the commenting style the same, so `//!` instead of `/*!`

2020-09-07 13:17 UTC, rljacobson commented on src/hashmap.rs
> +use std::borrow::Borrow;
To clarify, you want only the hashmap in `src/lib.rs`? (Hashmap code wasn't changed, just copied+pasted.)

2020-09-07 13:18 UTC, rljacobson commented on src/lib.rs
> +/*!
*facepalm* Of course!

2020-09-07 13:48 UTC, JelteF commented on src/hashmap.rs
> +use std::borrow::Borrow;
yeah, I think I'll move it to a separate file after merging this like you did. But to be able to review the PR easily I'd like the changes to be minimal.

2020-09-07 13:51 UTC, JelteF commented on src/hashmap.rs
> +use std::borrow::Borrow;
So with that the final changes should be:
1. Add `set_default` to `DefaultHashMap` in `src/lib.rs`
2. Add a `src/btreemap.rs` with your new btree code (with serde support copy pasted from defaulthashmap too).

2020-09-07 14:09 UTC, rljacobson commented on src/hashmap.rs
> +use std::borrow::Borrow;
Yep, makes sense. In retrospect, I should have made two PRs: one for `DefaultBTreeMap` and one for `set_default`.

2020-09-07 14:20 UTC, JelteF commented on src/hashmap.rs
> +use std::borrow::Borrow;
Yeah that would have been even better, but `set_default` is small enough that it's fine to have them together this time.

2020-09-07 15:36 UTC, rljacobson commented
@JelteF Since I am revisiting this PR, I might as well "do it right." There are a few more methods from `BTreeMap` that I would like to implement:

- [ ] `append()`
- [ ] `range()`
- [ ] `range_mut()`
- [ ] `split_off()`

The `range()` (`range_mut()`) method requires an additional `Range` (resp. `RangeMut`) structure. It is not clear what the semantics of `range()` should be. It could match that of `get()` in the sense that any key for which the map contains no value will produce `(&key, &self.default)`. The alternative is that it matches the behavior of `keys` and skips over missing keys. The latter semantics makes more sense to me. A counter-argument is that then `range()` and `range_mut()` would give a different sequence—unless you have `range_mut()` work differently from `get_mut()`.

While I am at it, should I implement the missing `HashMap` methods? They are:

- [ ] `iter_mut()`
- [ ] `remove_entry()`
- [ ] `with_capacity()`
- [ ] `get_key_value()`

I have excluded methods related to using a custom `Hasher`. To be blunt, I don't know anything about how custom `Hashers`, so it's easier to keep kicking that can down the road until someone wants it.

And since I am thinking about this, I would also like to implement an alternative semantics indicated by a new enum with variants `InsertOnRead` and `InsertOnWrite`. But this is an entirely separate PR. I'll open an issue to discuss it.

2020-09-07 15:44 UTC, JelteF commented
I would say lets do those extra methods in an upcoming PR, since there might be more discussion points.

2020-09-07 15:45 UTC, JelteF commented
You could create the PR already if you want though, but I don't think it should block merging this PR.

2020-09-07 19:19 UTC, rljacobson commented
Bit of a noob question, but how do I rebase my changes to the new upstream commit and keep the PR clean? Normally I would put my changes on a new branch, reset master to before my changes, `git pull` the upstream commits, and then rebase my new changes branch onto the updated master branch. But then to sync my github repo, wouldn't I have to `git push --force`? Then what happens to the PR?

2020-09-07 19:28 UTC, JelteF commented
Force push to the same branch as the PR will update the PR automatically.
So the flow you describe is what you want indeed.

On Mon, 7 Sep 2020, 21:19 Robert Jacobson, <notifications@github.com> wrote:

> Bit of a noob question, but how do I rebase my changes to the new upstream
> commit and keep the PR clean? Normally I would put my changes on a new
> branch, reset master to before my changes, git pull the upstream commits,
> and then rebase my new changes branch onto the updated master branch. But
> then to sync my github repo, wouldn't I have to git push --force? Then
> what happens to the PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JelteF/defaultmap/pull/10#issuecomment-688481446>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI3YJTHF5TGNV64DX6UMADSEUW4RANCNFSM4QPYSS3Q>
> .
>

2020-09-07 19:33 UTC, rljacobson commented
Thanks. I'll do that and squash my commits.

2020-09-10 20:38 UTC, merged

2020-09-10 20:46 UTC, JelteF commented
Released this as 0.5.0